# Generated by Django 4.0.4 on 2022-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
