# Generated by Django 4.0.4 on 2022-06-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Public',
            new_name='Post_image',
        ),
    ]
